name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm ci # 'npm ci' é mais limpo para CI do que 'npm install'
          npm cache clean --force # Limpa o cache para garantir que não há binários corrompidos

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run cypress:run
          browser: chrome
          headless: true

        env:
          CI: true